public class BigMachinesParameters {
    
    // BigMachines parameters
    public static Boolean usesSSL =       true; // does BigMachines site use SSL?
    public static String bm_site =        'testblackboard'; // subdomain of BigMachines site
    public static String process_id =     '4614493'; // id of commerce process
    public static String action_id_copy = '4615146'; // id of commerce process's copy action
    public static String action_id_open = '4615140'; // id of commerce process's open action
    public static String document_id =    '4614563'; // id of main document in commerce process
    public static String version_id =     '4622363'; // version id    
    public static String process_var =    'quotes_process_bmClone_16'; // variable name of commerce process

}